//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projrct_home.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register_Table
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string CW { get; set; }
        public string DW { get; set; }
        public string CPlan { get; set; }
        public string Trainer { get; set; }
        public string Before { get; set; }
        public string Profile { get; set; }
        public string RegDate { get; set; }
    }
}
